services:
  - type: web
    name: aitco-web
    env: python
    pythonVersion: "3.10.0"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    plan: free
